---
title: "Distance calculation testing"
author: "Håkon Kaspersen"
date: '`r format(Sys.time(), "%d.%m.%Y")`'
always_allow_html: yes
output:
    html_document:
      code_folding: hide
      df_print: paged
      highlight: kate
      number_sections: yes
      theme: flatly
      toc: yes
      toc_depth: 3
      toc_float:
        collapsed: yes
    pdf_document:
      toc: yes
      toc_depth: '3'
---

```{r}
pacman::p_load(dplyr, ggtree, ape, tibble, cluster)
```


```{r}
testdata_tree <- read.delim("../data/test_data_cgMLST_funksjon.txt", sep = "\t", header = TRUE, stringsAsFactors = TRUE) %>%
  select(-X) %>%
  column_to_rownames("ref")

print("Raw data without NA's:")
testdata_tree

test_tree <- as.phylo(hclust(daisy(testdata_tree, metric="gower")))

print("Daisy function calculation on raw data without NAs:")
daisy(testdata_tree, metric = "gower")

print("Distances calculated on the raw data without NA's with cophenetic.phylo:")
cophenetic.phylo(test_tree)

ggtree(test_tree)+
  geom_tiplab()

testdata_tree_NA1 <- testdata_tree %>%
  mutate(g4 = ifelse(g1 == 6, NA, g4))

row.names(testdata_tree_NA1) <- c("A","B","C","D","E")

print("Raw data with NA's:")
testdata_tree_NA1

test_tree2 <- as.phylo(hclust(daisy(testdata_tree_NA1, metric="gower")))

print("Daisy function calculation on raw data with one NA:")
daisy(testdata_tree_NA1, metric = "gower")

print("Distances calculated on the raw data with one NA with cophenetic.phylo:")
cophenetic.phylo(test_tree2)

ggtree(test_tree2)+
  geom_tiplab()





```

# dist vs. daisy
```{r}
print("Dataset without NA's:")

x <-
  as.data.frame(matrix(
    c(
      "5",
      "8",
      "13",
      "10",
      "15",
      "6",
      "8",
      "13",
      "10",
      "15",
      "7",
      "9",
      "13",
      "10",
      "15",
      "4",
      "12",
      "16",
      "10",
      "15",
      "4",
      "12",
      "20",
      "10",
      "15"
    ),
    ncol = 5,
    byrow = T
  ))

x

test1 <- as.phylo(hclust(dist(x, method = "manhattan")))
test2 <- as.phylo(hclust(daisy(x, metric = "gower")))

print("Test with dist:")
cophenetic.phylo(test1)
ggtree(test1) +
  geom_tiplab()


print("Test with daisy:")
cophenetic.phylo(test2)
ggtree(test2) +
  geom_tiplab()

print("Dataset with NA's:")
# Med NA'er
x_na <-
  as.data.frame(matrix(
    c(
      "5",
      "8",
      "13",
      "10",
      "15",
      "6",
      "8",
      NA,
      "10",
      "15",
      "7",
      "9",
      "13",
      "10",
      "15",
      "4",
      "12",
      "16",
      "10",
      "15",
      "4",
      "12",
      "20",
      "10",
      "15"
    ),
    ncol = 5,
    byrow = T
  ))

x_na

test1_na <- as.phylo(hclust(dist(x_na)))
test2_na <- as.phylo(hclust(daisy(x_na, metric = "gower")))

print("Test with dist:")
cophenetic.phylo(test1_na)
ggtree(test1_na) +
  geom_tiplab()

print("Test with daisy:")
cophenetic.phylo(test2_na)
ggtree(test2_na) +
  geom_tiplab()

```

