---
title: "Quality control - Mash screen"
author: "Håkon Kaspersen"
date: '`r format(Sys.time(), "%d.%m.%Y")`'
always_allow_html: yes
output:
    html_document:
      code_folding: hide
      df_print: paged
      highlight: kate
      number_sections: yes
      theme: flatly
      toc: yes
      toc_depth: 3
      toc_float:
        collapsed: yes
    pdf_document:
      toc: yes
      toc_depth: '3'
---

```{r}
pacman::p_load(ggplot2, dplyr, tidyr, stringr, purrr, viridis)
```

```{r}
func_paste <- function(x) paste(unique(x[!is.na(x)]), collapse = ", ")

scan_max <- function(x) max(scan(text = x, what = "", sep = ",", quiet = TRUE, strip.white = TRUE))

# Identifies filenames in input folder
file_names_mash <- function(filepath) {
  files <- list.files(path = filepath, pattern = "_mash.out")
  return(files)
}

# Import ariba data from report.tsv from chosen database used in ariba
get_mash_data <- function(filepath) {
  files <- file_names_mash(filepath)
  
  data_list <- lapply(files,
                      FUN = function(file) {
                        read.delim(
                          paste0(filepath, "/", file),
                          stringsAsFactors = F,
                          header = FALSE, # no header in files
                          quote = "", # disable quoting, avoid EOS error
                          sep = "\t"
                        )
                      })
  
  names(data_list) <- files # set name of each df in list 
  data <- bind_rows(data_list, .id = "ref") %>% # bind to data frame
    rename("identity" = V1,
           "shared_hashes" = V2,
           "median_multiplicity" = V3,
           "p_value" = V4,
           "query_id" = V5,
           "query_comment" = V6) %>%
    mutate(p_value = round(p_value, 5))
  return(data)
}

id_data <- read.table("../data/id.txt",
                      sep = "\t",
                      header = TRUE,
                      stringsAsFactors = F)

filepath <- "../data/mash/"

mash_raw <- get_mash_data(filepath) %>%
  mutate(ref = sub("_L00[0-9]_R1_001.fastq.gz_mash.out", "", ref)) %>%
  left_join(id_data, by = "ref") %>%
  select(-ref) %>%
  select(id, everything())

```

```{r}
mash_results <- mash_raw %>%
  separate(shared_hashes, c("min","max"), sep = "/", remove = FALSE) %>%
  mutate(test = as.numeric(min)/as.numeric(max)) %>%
  select(-c(min, max)) %>%
  filter(test >= 0.1) %>%
  mutate(species = query_comment %>%
           str_replace("\\[.*?\\] ", "") %>%
           sub("^.+_.+\\.[0-9] (.*?), .+", "\\1", .) %>%
           word(1,2),
         phage = grepl("phage", ignore.case = T, species)) %>%
  filter(phage == FALSE) %>%
  {. ->> mash_plot_df} %>%
  select(-phage) %>%
  spread(species, identity)
```

# Identity plot for all isolates

```{r, fig.width=10, fig.height=8}
ggplot(mash_plot_df, aes(id, identity, fill = species)) +
  geom_point(pch = 21, size = 2)+
  geom_hline(yintercept = 0.95, alpha = 0.5)+
  scale_fill_brewer(type = "div", palette = 2)+
  labs(y = "Identity",
       x = "Samples")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        legend.title = element_blank(),
        axis.ticks.x = element_blank())
```

# Contaminated Isolates
```{r}
test <- mash_plot_df %>%
  filter(species != "Escherichia coli",
         identity >= 0.95) %>%
  select(id)

ids <- test$id

test2 <- mash_plot_df %>%
  select(-c(phage,shared_hashes,query_id,query_comment,median_multiplicity,test,p_value)) %>%
  filter(id %in% ids) %>%
  mutate(id2 = 1:n()) %>%
  spread(species, identity, fill = NA) %>%
  select(-id2) %>%
  group_by(id) %>%
  summarise_all(funs(func_paste)) %>%
  mutate(`Escherichia coli` = sapply(`Escherichia coli`, scan_max)) %>%
  mutate_all(funs(gsub("^$", NA, .)))

```

